{% set name = "python-lsp-black" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8286d2d310c566844b3c116b824ada6fccfa6ba228b1a09a0526b74c04e0805f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - black >=23.11.0
    - python-lsp-server >=1.4.0
    - tomli

test:
  imports:
    - pylsp_black
    - pylsp_black.plugin

about:
  home: https://github.com/python-lsp/python-lsp-black
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Black plugin for the Python LSP Server
  dev_url: https://github.com/python-lsp/python-lsp-black

extra:
  recipe-maintainers:
    - andfoy
    - ccordoba12
    - steff456
    - dalthviz
